# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.1’

pod 'Fabric'
pod 'Crashlytics'

target 'reactNativeHelloAgainWorld' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for reactNativeHelloAgainWorld
   pod 'MotionDnaSDK'


end


